name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version to be published (x.y.z)'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create venv & install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Bump version in config.json
        run: |
          source venv/bin/activate
          python scripts/update_version.py ${{ github.event.inputs.version }}

      - name: Build package
        run: |
          source venv/bin/activate
          python3 setup.py sdist bdist_wheel

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          source venv/bin/activate
          twine upload dist/*
